name: Float CI

# This workflow runs on any PR/Push requests to any branch except push requests to 'main', it runs test cases and leave PR comment with the test coverage.
on:
  push:
    branches-ignore:
      - 'main'
    pull_request:
      branches:
        - '*'

# permissions for actions to comment on pull requests and install dependencies
permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js '22'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm' # caching npm dependencies into pack-lock.json
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        id: tests
        continue-on-error: true # run rest of steps even if tests failed.
        run: npm test -- --coverage

      - name: Comment Test Coverage
        uses: AthleticNet/comment-test-coverage@1.1
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./coverage/coverage-summary.json

      # fail workflow if the tests failed.
      - name: Check test results
        if: steps.tests.outcome == 'failure'
        run: exit 1
